# Generated by Django 5.2.6 on 2025-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPDPoint',
            fields=[
                ('cpd_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_earned', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CPD Point',
                'verbose_name_plural': 'CPD Points',
                'db_table': 'cpd_point',
            },
        ),
    ]
