# Generated by Django 5.2.6 on 2025-09-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_remove_caseassignment_lawyer_id_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPDPoint",
            fields=[
                ("cpd_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("points_earned", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="cases.case",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lawyerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "CPD Point",
                "verbose_name_plural": "CPD Points",
                "db_table": "cpd_point",
            },
        ),
    ]
