# Generated by Django 5.2.6 on 2025-09-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpd", "0002_cpdpoint_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpdpoint",
            name="user",
        ),
    ]
