# Generated by Django 5.2.6 on 2025-10-04 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpd", "0004_alter_cpdpoint_lawyer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpdpoint",
            name="lawyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "lawyer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
