# Generated by Django 5.2.6 on 2025-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("applicant", "Applicant"),
                    ("lawyer", "Lawyer"),
                    ("lsk_admin", "LSK Admin"),
                    ("admin", "Admin"),
                ],
                default="applicant",
                max_length=100,
            ),
        ),
    ]
