# Generated by Django 5.2.5 on 2025-09-08 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("lawyer_id", models.IntegerField()),
                ("case_id", models.IntegerField()),
                ("is_assigned", models.BooleanField(default=True)),
                ("assign_date", models.DateTimeField(auto_now_add=True)),
                ("reject_reason", models.TextField(blank=True, null=True)),
                ("confirmed_by_applicant", models.BooleanField(default=False)),
                ("confirmed_by_lawyer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Detainee",
            fields=[
                ("detainee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=20
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "relation_to_applicant",
                    models.CharField(
                        choices=[("family", "Family"), ("other", "Other")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("case_description", models.TextField()),
                (
                    "predicted_case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("criminal", "Criminal"),
                            ("civil", "Civil"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "predicted_urgency_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_offense", models.DateField(blank=True, null=True)),
                ("trial_date", models.DateField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "income_source",
                    models.CharField(
                        blank=True,
                        choices=[("informal", "Informal"), ("formal", "Formal")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("less_than_30000", "Less than 30000"),
                            ("greater_than_30000", "Greater than 30000"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dependents", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("handled", "Handled"),
                            ("arraignment", "Arraignment"),
                            ("bail", "Bail"),
                            ("trial", "Trial"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detainee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="cases.detainee",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("detainee_id", "case_description", "trial_date"),
                        name="unique_case_per_detainee_description_trialdate",
                    )
                ],
            },
        ),
    ]
