# Generated by Django 5.2.5 on 2025-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("detainee_id", models.IntegerField()),
                ("case_description", models.TextField()),
                (
                    "predicted_case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("criminal", "Criminal"),
                            ("civil", "Civil"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "predicted_urgency_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_offense", models.DateField(blank=True, null=True)),
                ("trial_date", models.DateField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "income_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dependents", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("handled", "Handled"),
                            ("arraignment", "Arraignment"),
                            ("bail", "Bail"),
                            ("trial", "Trial"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
