# Generated by Django 5.0.6 on 2025-09-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("case_description", models.TextField()),
                (
                    "predicted_case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("criminal", "Criminal"),
                            ("civil", "Civil"),
                            (
                                "constitutional and human rights",
                                "Constitutional and Human Rights",
                            ),
                            ("family", "Family"),
                            ("labor", "Labor"),
                            ("property", "Property"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "predicted_urgency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_of_offense", models.DateField(blank=True, null=True)),
                ("trial_date", models.DateField(blank=True, null=True)),
                (
                    "police_station",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        blank=True,
                        choices=[("informal", "Informal"), ("formal", "Formal")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("less_than_30000", "Less than 30000"),
                            ("greater_than_30000", "Greater than 30000"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dependents", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("handled", "Handled"),
                            ("arraignment", "Arraignment"),
                            ("bail", "Bail"),
                            ("trial", "Trial"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Detainee",
            fields=[
                ("detainee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=20
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "relation_to_applicant",
                    models.CharField(
                        choices=[("family", "Family"), ("other", "Other")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_assigned", models.BooleanField(default=True)),
                ("assign_date", models.DateTimeField(auto_now_add=True)),
                ("reject_reason", models.TextField(blank=True, null=True)),
                ("confirmed_by_applicant", models.BooleanField(default=False)),
                ("confirmed_by_lawyer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="cases.case",
                    ),
                ),
            ],
        ),
    ]
