# Generated by Django 5.2.5 on 2025-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                fields=("detainee_id", "case_description", "trial_date"),
                name="unique_case_per_detainee_description_trialdate",
            ),
        ),
    ]
