# Generated by Django 5.2.5 on 2025-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_detainee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="detainee",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="detainee",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
