# Generated by Django 5.2.5 on 2025-09-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_prison_location_alter_case_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="prison_location",
            new_name="police_station",
        ),
    ]
