# Generated by Django 5.2.5 on 2025-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_detainee_first_name_detainee_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detainee",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="detainee",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
