# Generated by Django 5.2.6 on 2025-09-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_rename_prison_location_case_police_station"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseassignment",
            name="lawyer_id",
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="lawyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="users.lawyerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="predicted_case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("criminal", "Criminal"),
                    ("civil", "Civil"),
                    (
                        "constitutional and human rights",
                        "Constitutional and Human Rights",
                    ),
                    ("family", "Family"),
                    ("labor", "Labor"),
                    ("property", "Property"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="predicted_urgency_level",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="detainee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "applicant"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
