# Generated by Django 5.2.6 on 2025-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_remove_caseassignment_lawyer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="predicted_case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("criminal", "Criminal"),
                    ("Environment", "environment"),
                    ("Employment", "employment"),
                    ("civil", "Civil"),
                    (
                        "constitutional and human rights",
                        "Constitutional and Human Rights",
                    ),
                    ("family", "Family"),
                    ("labor", "Labor"),
                    ("property", "Property"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
