# Generated by Django 5.2.5 on 2025-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_alter_detainee_first_name_alter_detainee_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("lawyer_id", models.IntegerField()),
                ("case_id", models.IntegerField()),
                ("is_assigned", models.BooleanField(default=True)),
                ("assign_date", models.DateTimeField(auto_now_add=True)),
                ("reject_reason", models.TextField(blank=True, null=True)),
                ("confirmed_by_applicant", models.BooleanField(default=False)),
                ("confirmed_by_lawyer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
