# Generated by Django 5.2.6 on 2025-09-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_case_predicted_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("handled", "Handled"),
                    ("arraignment", "Arraignment"),
                    ("bail", "Bail"),
                    ("trial", "Trial"),
                    ("completed", "Completed"),
                ],
                default="In Progress",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
