# Generated by Django 5.2.5 on 2025-09-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_caseassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("case_description", models.TextField()),
                (
                    "predicted_case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("criminal", "Criminal"),
                            ("civil", "Civil"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "predicted_urgency_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_offense", models.DateField(blank=True, null=True)),
                ("trial_date", models.DateField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "income_source",
                    models.CharField(
                        blank=True,
                        choices=[("informal", "Informal"), ("formal", "Formal")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("less_than_30000", "Less than 30000"),
                            ("greater_than_30000", "Greater than 30000"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dependents", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("handled", "Handled"),
                            ("arraignment", "Arraignment"),
                            ("bail", "Bail"),
                            ("trial", "Trial"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detainee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="cases.detainee",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("detainee_id", "case_description", "trial_date"),
                        name="unique_case_per_detainee_description_trialdate",
                    )
                ],
            },
        ),
    ]
