# Generated by Django 5.2.6 on 2025-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_alter_case_stage_alter_case_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
