# Generated by Django 5.2.6 on 2025-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_alter_case_stage_alter_case_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("being_handled", "Being Handled"),
                    ("arraignment", "Arraignment"),
                    ("bail", "Bail"),
                    ("trial", "Trial"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
