# Generated by Django 5.2.6 on 2025-10-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_alter_case_stage_alter_case_status"),
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("handled", "Handled"),
                    ("arraignment", "Arraignment"),
                    ("bail", "Bail"),
                    ("trial", "Trial"),
                    ("completed", "Completed"),
                ],
                default="In Progress",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="lawyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="users.lawyerprofile",
            ),
        ),
    ]
