# Generated by Django 5.2.6 on 2025-10-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_alter_case_stage_alter_case_status_and_more"),
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="assignment_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="rejection_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("handled", "Handled"),
                    ("arraignment", "Arraignment"),
                    ("bail", "Bail"),
                    ("trial", "Trial"),
                    ("completed", "Completed"),
                ],
                default="in_progress",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_assignment", "Pending Assignment"),
                    (
                        "assigned_pending_lawyer_acceptance",
                        "Assigned - Pending Lawyer Acceptance",
                    ),
                    ("accepted", "Accepted by Lawyer"),
                    ("rejected", "Rejected by Lawyer"),
                    ("completed", "Completed"),
                    ("unassignable", "Unassignable - Contact Admin"),
                ],
                default="pending_assignment",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="users.lawyerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("timed_out", "Timed Out"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
