# Generated by Django 5.2.6 on 2025-10-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_case_assignment_attempts_and_more"),
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="case",
            name="unique_case_per_detainee_description_trialdate",
        ),
        migrations.RemoveField(
            model_name="case",
            name="assignment_attempts",
        ),
        migrations.RemoveField(
            model_name="caseassignment",
            name="rejection_count",
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="reassigned_automatically",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("assignment_failed", "Assignment Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="lawyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="users.lawyerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("reassigned", "Reassigned"),
                    ("handled", "Handled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                fields=("detainee", "case_description", "trial_date"),
                name="unique_case_per_detainee_description_trialdate",
            ),
        ),
    ]
