# Generated by Django 5.2.6 on 2025-10-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0012_remove_case_unique_case_per_detainee_description_trialdate_and_more",
        ),
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseassignment",
            name="assignment_id",
        ),
        migrations.AddField(
            model_name="case",
            name="assigned_lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_cases",
                to="users.lawyerprofile",
            ),
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("handled", "Handled"),
                    ("arraignment", "Arraignment"),
                    ("bail", "Bail"),
                    ("trial", "Trial"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="in_progress",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("reassigned", "Reassigned"),
                    ("assignment_failed", "Assignment Failed"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases_assigned",
                to="users.lawyerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="caseassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("reassigned", "Reassigned"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
