# Generated by Django 5.2.6 on 2025-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_remove_caseassignment_assignment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseassignment",
            name="id",
        ),
        migrations.AddField(
            model_name="caseassignment",
            name="assignment_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
