# Generated by Django 5.2.6 on 2025-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_remove_caseassignment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="assigned_lawyer",
        ),
    ]
