name: Automated API tests using Postman CLI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: macos-latest
    env:
      COL_UID: "45725952-29a5534b-d4a0-4607-9596-4efcd08493b0"
      ENV_UID: "44876583-8ef5b223-15f5-438c-a9c1-eadfdee6eabf"
      POSTMAN_API_KEY: "PMAK-68c40dc5faf76f0001d9eff1-b4b829e2707e493f3bf0793db697dde514"

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh

      - name: Debug Environment & Collection IDs
        run: |
          echo "=== DEBUG INFO ==="
          echo "COL_UID: $COL_UID"
          echo "ENV_UID: $ENV_UID"
          echo "POSTMAN_API_KEY starts with: ${POSTMAN_API_KEY:0:5}..."
          if [[ -z "$COL_UID" ]]; then echo "COL_UID is empty!"; exit 1; fi
          if [[ -z "$ENV_UID" ]]; then echo "ENV_UID is empty!"; exit 1; fi
          if [[ -z "$POSTMAN_API_KEY" ]]; then echo "POSTMAN_API_KEY is empty!"; exit 1; fi

      - name: Login to Postman CLI
        run: postman login --with-api-key "$POSTMAN_API_KEY"

      - name: Run API tests
        run: |
          mkdir -p reports
          postman collection run "$COL_UID" -e "$ENV_UID" \
            --reporters cli,junit \
            --reporter-junit-export reports/junit.xml

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: postman-junit
          path: reports/junit.xml